name: Build Orange ModLoader

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
permissions:
  contents: write
jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
      - name: Build APK
        working-directory: modframework-ui
        run: gradle composeApp:assembleDebug
      - name: Upload APK to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: modframework-ui/composeApp/build/outputs/apk/debug/*.apk

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
      - name: Build MSI
        working-directory: modframework-ui
        run: gradle packageMsi
      - name: Upload MSI to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: modframework-ui/composeApp/build/compose/binaries/main/msi/*.msi